services:
  discordbot:
    depends_on:
      - database
    image: discordbot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: database
      DB_USER: discordbot
      DB_PASSWORD_FILE: /run/secrets/database_password
      TOKEN_FILE: /run/secrets/token
    secrets:
      - database_password
      - token
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 AnnouncerBot.py "]
    ports:
      - 5678:5678
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/database_root_password
      MYSQL_DATABASE: servers
      MYSQL_USER: discordbot
      MYSQL_PASSWORD_FILE: /run/secrets/database_password
    secrets:
      - database_root_password
      - database_password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
secrets:
  database_root_password:
    file: ./database_root_password.txt
  database_password:
    file: ./database_password.txt
  token:
    file: ./token.txt